version: "3.9"

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - "3000:3000"
    env_file:
      - ./apps/reservations/.env
    volumes:
      - ./apps/reservations:/usr/src/app/apps/reservations
      - ./libs:/usr/src/app/libs
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=300                # <--- numeric interval in ms (important)
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=300      # <--- numeric interval in ms

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - "3001:3001"
    env_file:
      - ./apps/auth/.env
    volumes:
      - ./apps/auth:/usr/src/app/apps/auth
      - ./libs:/usr/src/app/libs
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=300
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=300

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: { }
