apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: europe-central2-docker.pkg.dev/eternal-cocoa-446320-u0/payments/production
          name: payments
          env:
            - name: PORT
              value: "3001"
            - name: NOTIFICATIONS_HOST
              value: notifications # service name
            - name: NOTIFICATIONS_PORT
              value: "3000"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiKey
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi

